### ISSUE TITLE
chane settings to use {{}} issue

### ISSUE THREAD

**Issue by vitaliiznak** [danlevan/express-dot-engine#12]
When I changed to use {{ }} instead of [[ ]] the partial dont work anymore
// doT settings

engine.settings.dot = {
  evaluate:    /[[([\s\S]+?)]]/g,
  interpolate: /[[=([\s\S]+?)]]/g,
  encode:      /[[!([\s\S]+?)]]/g,
  use:         /[[#([\s\S]+?)]]/g,
  define:      /[[##\s_([\w.$]+)\s_(:|=)([\s\S]+?)#]]/g,
  conditional: /[[\?(\?)?\s_([\s\S]_?)\s_]]/g,
  iterate:     /[[~\s_(?:]]|([\s\S]+?)\s_:\s_([\w$]+)\s_(?::\s_([\w$]+))?\s*]])/g,
  varname: 'layout, model',
  strip: false,
  append: true,
  selfcontained: false,
};

then
{{= partial('path/test')}} - partials is not defined

**Comment by 8lueberry** [comment]
In version 1.0.6, varname should include partial too.

```
...
varname: 'layout, partial, locals, model',
```

Let me know if that works.

**Comment by vitaliiznak** [comment]
it works, thanks, sorry for delay

**Comment by vitaliiznak** [comment]
yeap, it works but only on the same order i mean 
varname: 'layout, partial, locals, model', - works 
varname: 'layout, locals, model, partial', - does not work

**Comment by 8lueberry** [comment]
Yes, order is important :)

I'll update the doc soon. Thanks!
