### ISSUE TITLE
Make syntax change more obvious.

### ISSUE THREAD

**Issue by quadrupleslap** [danlevan/express-dot-engine#4]
It's really nice, but could you please make it more obvious that you changed the {{}} to [[]] ?
I spent half an hour trying to figure out what was wrong, completely forgetting to rtm. It'd be nice if you put it at the top of readme.md =)

**Comment by 8lueberry** [comment]
Sorry about that :) I will make an update soon and I'll put that in the readme.
Thanks for your feedback :)

**Comment by 8lueberry** [comment]
I added a section at the top of the readme in version 1.0.1
